language: node_js
nvm:

matrix:
  include:
  - node_js: "6"
    script: npm install proxy-agent@2.0.0 && npm run test-with-temp-cloud
  - node_js: "8"
    script: npm run test-with-temp-cloud
  - node_js: "10"
    script: npm run test-with-temp-cloud
  - node_js: "12"
    script: npm run test-with-temp-cloud
  - node_js: "14"
    script: npm run test-with-temp-cloud
  - node_js: "16"
    script: npm run test-with-temp-cloud

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
