language: node_js
nvm:

matrix:
  include:
  - node_js: "6"
    script: npm run test-es5
  - node_js: "8"
    script: npm run test-es6
  - node_js: "10"
    script: npm run test-es6
  - node_js: "12"
    script: npm run test
